# Generated by Django 2.2 on 2019-06-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190607_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duration_number',
            new_name='duration',
        ),
    ]
