# Generated by Django 2.2 on 2019-06-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190607_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Teen cinema', 'Teen cinema'), ('Cinema art', 'Cinema art'), ('BDSM cinema', 'BDSM cinema'), ('War movies', 'War movies'), ('Gangster cinema', 'Gangster cinema'), ('Cinema catastrophe', 'Cinema catastrophe'), ('Costumbrista cinema', 'Costumbrista cinema'), ('Christian cinema', 'Christian cinema'), ('Action cinema', 'Action cinema'), ('Animation film', 'Animation film'), ('Martial arts cinema', 'Martial arts cinema'), ('Author cinema', 'Author cinema'), ('Adventure Movies', 'Adventure Movies'), ('Science fiction movies', 'Science fiction movies'), ('Mystery cinema', 'Mystery cinema'), ('Samurai cinema', 'Samurai cinema'), ('Horror movies', 'Horror movies'), ('Documentary film', 'Documentary film'), ('Epic cinema', 'Epic cinema'), ('Erotic cinema (not pornographic)', 'Erotic cinema (not pornographic)'), ('Experimental cinema', 'Experimental cinema'), ('Fantastic movies', 'Fantastic movies'), ('Fetish cinema', 'Fetish cinema'), ('Historical cinema', 'Historical cinema'), ('Musical cinema', 'Musical cinema'), ('Black cinema', 'Black cinema'), ('Film peplum', 'Film peplum'), ('Police cinema', 'Police cinema'), ('Political cinema', 'Political cinema'), ('Pornographic movies', 'Pornographic movies'), ('Propaganda cinema', 'Propaganda cinema'), ('Romantic cinema', 'Romantic cinema'), ('Cinema S', 'Cinema S'), ('Surreal cinema', 'Surreal cinema'), ('Underground cinema', 'Underground cinema'), ('Class B', 'Class B'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Dramedia', 'Dramedia'), ('Melodrama', 'Melodrama'), ('Snuff movies', 'Snuff movies'), ('Road movie', 'Road movie'), ('Spoof movie', 'Spoof movie'), ('Thriller', 'Thriller'), ('Western', 'Western')], default='Anime', max_length=25),
            preserve_default=False,
        ),
    ]
