# Generated by Django 2.2 on 2019-06-11 19:26

import apps.movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190611_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=apps.movies.models.movie_directory_path),
        ),
    ]
